### ISSUE TITLE
How to "cancel" an illusory animation

### ISSUE THREAD

**Issue by 719media** [justintaddei/illusory#13]
Is there a way to cancel an illusory animation?

Think about "canceling" an animation because of clicking on a toggle twice

It would probably be better to have the animation "finish" (so appropriate hooks are fired) instantly, instead of just deleting it.
Thoughts?

**Comment by justintaddei** [comment]
That is not currently possible (Well... I suppose you could save a reference to the `from` and `to` elements in `beforeAnimate` and then use `Element.prototype.remove` but that's far from a good solution).



> It would probably be better to have the animation "finish" (so appropriate hooks are fired) instantly, instead of just deleting it.
> Thoughts?

Hm.. maybe introducing more hooks would be better? Say, for example, `beforeCancel` and return a `completed` boolean.  You might not always want the same hooks to fire for both normal finishes and canceled ones.

```js
const completed = await illusory(from, to, {
    beforeCancel(fromClone, toClone) {
        // Accept promises so you can fade-out/other work before actually removing everything.
        return Promise.resolve()
    }
})

if (!completed) // Canceled
````

**The problem**
How do you actually cancel the animation? Currently `illusory(...)` returns a `Promise` that resolves when the animation completes. I don't want to do the weird "callback that takes a callback that returns a function that you call to do something" thing as we did in `v-shared-element`. If that means a breaking change, then I guess so be it.

Right now, all I can think to do is change the API to return an Object with this shape:
```ts
interface {
    done: Promise<void>
    cancel: () => void
}
``` 

That would open the door for more advanced features in the future:
```ts
interface {
    done: Promise<void>
    cancel: () => void
    pause: () => void
    reverse: () => void
    play: () => void
    isPause: boolean
    isReversed: boolean
}
``` 

Just a thought... those features would require a major refactor of the library to use either CSS animation or the Web Animation API when it has better support.

Let me know what you think.

**Comment by 719media** [comment]
Returning an object makes sense. It's extendible, and works for me. In the done() callback, would be good/useful to know if the animation finished normally, or was cancelled.

**Comment by justintaddei** [comment]
I was thinking of `done` as just a Promise (although it probably should return a `boolean` instead of `void`).

My idea for using it looked like this:

```js
const controller = illusory(...)

const completed = await controller.done

if (completed) // it was canceled.
``

What did you have in mind?

**Comment by justintaddei** [comment]
### API Proposal

```ts
interface IllusoryController {
    // Fired when transition ends, and the cloned elements have been remove from the DOM.
    // Resolves to a boolean indicating if the transition completely normally.
    done: Promise<boolean>
    // Method that, when called, immediately aborts the transition (`beforeDetach` is called, the clones are removed from the DOM, and `done` resolves to `false`)
    abort(): void
    // Reverses the transition so the elements appear to return to their original position. (Can be called again play the transition in the normal direction?)
    reverse(): void
    // `true` if the transition is reversed
    isReversed: boolean
}
```

```ts
beforeDetach(from: IllusoryElement, to: IllusoryElement, aborted: boolean)
```

**Comment by justintaddei** [comment]
Resolved with the addition of the "Controls API" in v2.0.0
